# Wow, I'm finally on Github Action

name: Build and Deploy My Wedding Invitation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Build!
        run: |
          npm install
          npm run build
      
      - uses: peaceiris/actions-gh-pages@v4
        permissions:
          contents: write
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build